### ISSUE TITLE
worldのそれぞれのページ作成

### ISSUE THREAD

**Issue by tsutoringo** [freeserverproject/freeserver-wiki#10]
- [x] #30
- [x] メインワールド
- [x] #28 
- [x] #29 
- [x] world/index.mdの作成

**Comment by Nakatai-0322** [comment]
先にこっち取り掛かります，

**Comment by Nakatai-0322** [comment]
seichi.mdをworld/seichi.mdに移動はやり方わかんないので誰か権限あってやり方分かる人お願いしやす。

**Comment by tsutoringo** [comment]
あい

**Comment by tsutoringo** [comment]
@Nakatai-0322 遅くなった〜

**Comment by Nakatai-0322** [comment]
> @Nakatai-0322 遅くなった〜

あざます～！

**Comment by Nakatai-0322** [comment]
https://github.com/freeserverproject/freeserver-wiki/pull/28
https://github.com/freeserverproject/freeserver-wiki/pull/29

**Comment by Nakatai-0322** [comment]
> #28
> #29

記事のベースだけつくったんで，あとから写真付け足します。

**Comment by Nakatai-0322** [comment]
#28 #29
完了しました。

**Comment by Nakatai-0322** [comment]
完了しましたんでクローズしますね。
