### ISSUE TITLE
規約へのリンク切れ(404リンク)

### ISSUE THREAD

**Issue by graycat27** [freeserverproject/freeserver-wiki#22]
トップページ、「関連リンク」の表
利用規約のリンクが存在しないアドレスへのリンクになっている

**Comment by Nakatai-0322** [comment]
https://github.com/freeserverproject/freeserver-wiki/commit/6d4eb347e2c5c296ec4d213f5e0fbfbfacd714cf
↑とりあえず対処しました。
（Googleドキュメント版の規約のみにしました。）

**Comment by Nakatai-0322** [comment]
https://github.com/freeserverproject/freeserver-wiki/commit/e4f116ae9af806e7743492d48d9c9a3e12e85d47
完了したっぽいのでクローズしますね。

**Comment by graycat27** [comment]
「利用規約」のWikiページを見ると「Discordサバの規約」「Minecraftサバの規約」の2つがあるのが分かります。
本件closeで問題ないとは思いますがね…。
