### ISSUE TITLE
ライセンスの追加

### ISSUE THREAD

**Issue by Nakatai-0322** [freeserverproject/freeserver-wiki#77]
「FREESERVER各Webページに関する規約」に於いては，ソースコード及び記事にCC BY-NC-ND 4.0ライセンスを適用すると記述があるためライセンスを追加をする，若しくは規約の改正を要望します。
※CC BY-NC-ND 4.0を適用した私がフォークしたレポジトリ:https://github.com/Nakatai-0322/freeserver-wiki

**Comment by Nakatai-0322** [comment]
※ライセンス追加の際はReadme.md及びWikiの記事全体に明示することをお勧めします。
[明示例]

[![](https://upload.wikimedia.org/wikipedia/commons/f/f1/Cc-by-nc-nd_icon.svg)](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ja)

このWikiの記事及びソースコードには[CC BY-NC-ND 4.0ライセンス](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ja)を適用しています。

**Comment by tsutoringo** [comment]
レポジトリにLICENSEを適用するのは却下かなぁ
理由としてはソースコードまでに適用したくないから
ただWikiの記事に明記する案はいいと思うので少し待って〜
